In [1]:
import numpy as np
import pandas as pd

# Question 1: Version of NumPy

In [2]:
np.__version__

'1.20.2'

# Question 2: Version of Pandas 

In [3]:
pd.__version__

'1.2.5'

In [4]:
np

<module 'numpy' from 'C:\\Users\\Chandra\\.conda\\envs\\dphi-tech\\lib\\site-packages\\numpy\\__init__.py'>

In [5]:
pd

<module 'pandas' from 'C:\\Users\\Chandra\\.conda\\envs\\dphi-tech\\lib\\site-packages\\pandas\\__init__.py'>

In [6]:
df = pd.read_csv("data.csv")

In [7]:
print(df.head(5))

  Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         C

In [8]:
df.shape

(11914, 16)

# Question 3: The average price of BMW

In [9]:
df_bmw = df[df[["Make",  'MSRP']]['Make']=="BMW"]
print(df_bmw.head(5))

  Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         C

In [10]:
df_bmw.shape

(334, 16)

In [11]:
average = df_bmw[['MSRP']].mean(axis=0)

In [12]:
print("average price of BMW cars=",average[0])

average price of BMW cars= 61546.76347305389


# Question 4: Number of missing values in "Engine HP" after 2015 *

In [13]:
df_year2015 = df[df[["Year",  'Engine HP']]['Year']>=2015]
print(df_year2015.head(5))

    Make       Model  Year                Engine Fuel Type  Engine HP  \
32  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34  FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41   BMW    2 Series  2016     premium unleaded (required)      240.0   
42   BMW    2 Series  2016     premium unleaded (required)      240.0   

    Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32               4.0            MANUAL  rear wheel drive              2.0   
33               4.0            MANUAL  rear wheel drive              2.0   
34               4.0            MANUAL  rear wheel drive              2.0   
41               4.0         AUTOMATIC  rear wheel drive              2.0   
42               4.0         AUTOMATIC  rear wheel drive              2.0   

       Market Category Vehicle Size Vehicle Style  highway MPG  city mpg  \
32         Performance

In [14]:
null_count = df_year2015['Engine HP'].isnull().sum()

In [15]:
print("Number of missing values in Engine HP after 2015 =",null_count)

Number of missing values in Engine HP after 2015 = 51


# Question 5: Does the mean change after filling missing values? *

In [16]:
df_temp = df

In [17]:
average = df[['Engine HP']].mean(axis=0)
print("average Engine HP in the dataset=",round(average[0]))

average Engine HP in the dataset= 249


In [18]:
df_temp['Engine HP'] = df['Engine HP'].fillna(round(average[0]))

In [19]:
null_count = df_temp['Engine HP'].isnull().sum()
null_count

0

In [20]:
averageNew = df[['Engine HP']].mean(axis=0)
print("New average Engine HP in the dataset=",round(averageNew[0]))

New average Engine HP in the dataset= 249


# Question 6

In [21]:
df_filter =  df[df['Make'] == 'Rolls-Royce']

In [22]:
df_filter.head(5)

Make            Model  Year             Engine Fuel Type  \
2921  Rolls-Royce         Corniche  2001  premium unleaded (required)   
3505  Rolls-Royce             Dawn  2016  premium unleaded (required)   
5275  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5276  Rolls-Royce  Ghost Series II  2015  premium unleaded (required)   
5277  Rolls-Royce  Ghost Series II  2016  premium unleaded (required)   

      Engine HP  Engine Cylinders Transmission Type     Driven_Wheels  \
2921      325.0               8.0         AUTOMATIC  rear wheel drive   
3505      563.0              12.0         AUTOMATIC  rear wheel drive   
5275      563.0              12.0         AUTOMATIC  rear wheel drive   
5276      563.0              12.0         AUTOMATIC  rear wheel drive   
5277      563.0              12.0         AUTOMATIC  rear wheel drive   

      Number of Doors                 Market Category Vehicle Size  \
2921              2.0                   Exotic,Luxury        Large   
3505              2.0  Exotic,Luxury,High-Performance        Large   
5275              4.0       Exotic,Luxury,Performance        Large   
5276              4.0       Exotic,Luxury,Performance        Large   
5277              4.0       Exotic,Luxury,Performance        Large   

     Vehicle Style  highway MPG  city mpg  Popularity    MSRP  
2921   Convertible           15        10          86  359990  
3505   Convertible           19        12          86  335000  
5275         Sedan           21        13          86  286750  
5276         Sedan           21        13          86  319400  
5277         Sedan           21        13          86  295850

In [23]:
df_filter.shape

(31, 16)

In [24]:
df_filter = df_filter[["Engine HP", "Engine Cylinders", "highway MPG"]]
df_filter.head(5)

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [25]:
df_filter.shape

(31, 3)

In [26]:
df_filter.drop_duplicates(inplace=True)
df_filter.head(5)

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5279      563.0              12.0           20
7443      322.0              12.0           15

In [27]:
df_filter.shape

(7, 3)

In [28]:
X = df_filter.to_numpy()

In [29]:
print(X)

[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]


In [30]:
XT = X.transpose()
print(XT)

[[325. 563. 563. 563. 322. 453. 624.]
 [  8.  12.  12.  12.  12.  12.  12.]
 [ 15.  19.  21.  20.  15.  19.  21.]]


In [31]:
XTX = XT.dot(X)
print(XTX)

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]


In [32]:
XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


In [33]:
sum = XTX_inverse.sum()
print("sum of all elements = ",sum)

sum of all elements =  0.032212320677486195


# Questions 7

In [34]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [35]:
W = (XTX_inverse.dot(XT)).dot(y)
print(W)

[ 0.19989598 31.02612262 31.65378877]
